export const generalSettings = [
  'NOTIFICATIONS AND EMAILS',
  'USER MANAGEMENT',
  'PHYSICAL LIBRARIES',
  'READING EVENTS',
  'INVOICING',
  'BOOK STATISTICS',
  'READERS STATISTICS',
  'EVENTS STATISTICS',
];

export const bookSettings = [
  'MANAGE GENRES',
  'BOOK VISIBILITY',
  'AUTHORS DATABASE',
  'BOOK COVERS',
  'BOOK COVERS',
];
